[package]
name = "telemetrie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
rppal = "0.17.1"
tokio = { version = "1.36.0", features = ["full"] }
nalgebra = "0.29.0"
bincode = "2.0.0-rc.3"
tokio-graceful-shutdown = "0.14.3"