[build]

[target.armv7-unknown-linux-gnueabihf]
linker = "D:\\Programmation\\VoitureRC\\toolchain\\arm-none-linux-gnueabihf\\bin\\arm-none-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]
